#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import https from 'node:https';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { ROOT } from '../src/resources.js';

/**
 * Build standalone executables that embed Node itself, so the app runs on a
 * machine with nothing installed.
 *
 * Node's Single Executable Application support works by injecting a blob into
 * a copy of the node binary. The blob is platform-independent, so one Linux
 * build machine can produce a Windows .exe by injecting into the official
 * Windows node.exe - which is what the win-x64 target below does.
 */

const BUILD = path.join(ROOT, 'build');
const DIST = path.join(ROOT, 'dist');

/**
 * Which Node to embed. Node 20 is used by default because its Windows binary is
 * ~15 MB smaller than Node 22's, which is the difference between a download that
 * fits in a plain .zip and one that does not - and a .zip is the only archive
 * every Windows version opens without extra software.
 *
 * The blob must be generated by the same Node version it is injected into, so
 * the matching Node is downloaded and used for that step rather than whichever
 * Node happens to be running this script.
 */
const NODE_VERSION = process.env.EMBED_NODE_VERSION || 'v20.20.2';

const ASSETS = [
  'config/scoring-rubric.json',
  'config/personas/larry.json',
  'samples/sample-practice-call.json',
  'src/web/index.html',
  'src/web/app.js',
  'src/web/styles.css',
  '.env.example',
  'README.md',
];

// The smoke-testable target is built first, so a broken blob is caught before
// the executables that cannot be run on this machine are declared good.
const TARGETS = {
  'linux-x64': { file: 'AI-Sales-Practice-linux', tarball: true, smokeTest: process.platform === 'linux' && process.arch === 'x64' },
  'win-x64': { file: 'AI-Sales-Practice.exe', url: `https://nodejs.org/dist/${NODE_VERSION}/win-x64/node.exe` },
};

const HOST = `${{ linux: 'linux', darwin: 'darwin' }[process.platform] || process.platform}-${process.arch}`;

/**
 * A Node of the embedded version that runs on THIS machine, used to generate the
 * blob - the blob has to be produced by the version it will be injected into,
 * and the constraint is the version, not the platform.
 */
async function hostNode() {
  if (process.version === NODE_VERSION) return process.execPath;
  if (process.platform === 'win32') {
    throw new Error(`Building on Windows requires running under node ${NODE_VERSION} itself (found ${process.version})`);
  }

  const binary = path.join(BUILD, `node-${NODE_VERSION}-${HOST}`, 'bin', 'node');
  if (fs.existsSync(binary)) return binary;

  const tarball = path.join(BUILD, `node-${NODE_VERSION}-${HOST}.tar.xz`);
  if (!fs.existsSync(tarball)) {
    process.stdout.write(`   downloading node ${NODE_VERSION} for ${HOST}... `);
    await download(`https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-${HOST}.tar.xz`, tarball);
    console.log('done');
  }
  execFileSync('tar', ['-C', BUILD, '-xf', tarball], { stdio: ['ignore', 'ignore', 'inherit'] });
  if (!fs.existsSync(binary)) throw new Error(`Could not find ${binary} after extracting`);
  return binary;
}

function bundle() {
  console.log('1. Bundling the app into a single file...');
  fs.mkdirSync(BUILD, { recursive: true });
  const out = path.join(BUILD, 'bundle.cjs');
  execFileSync(path.join(ROOT, 'node_modules', '.bin', 'esbuild'), [
    path.join(ROOT, 'src', 'main.js'),
    '--bundle',
    '--platform=node',
    // Must follow the Node being embedded, not the one running this build:
    // syntax esbuild leaves untransformed for a newer target fails at startup.
    `--target=node${NODE_VERSION.replace(/^v/, '').split('.')[0]}`,
    '--format=cjs',
    // ws pulls these in only if they are installed; it works fine without them.
    '--external:bufferutil',
    '--external:utf-8-validate',
    // Unused in packaged mode (ROOT comes from the executable's location), but
    // esbuild needs a value for it to compile the CommonJS bundle.
    '--define:import.meta.url="file:///sea-bundle"',
    `--outfile=${out}`,
  ], { stdio: ['ignore', 'ignore', 'inherit'] });
  console.log(`   ${(fs.statSync(out).size / 1024).toFixed(0)} KB`);
  return out;
}

async function buildBlob(bundlePath) {
  console.log(`2. Building the SEA blob with node ${NODE_VERSION} (app + assets)...`);
  const assets = Object.fromEntries(ASSETS.map((rel) => [rel, path.join(ROOT, rel)]));
  for (const [rel, file] of Object.entries(assets)) {
    if (!fs.existsSync(file)) throw new Error(`Asset missing: ${rel}`);
  }

  const configPath = path.join(BUILD, 'sea-config.json');
  fs.writeFileSync(configPath, JSON.stringify({
    main: bundlePath,
    output: path.join(BUILD, 'sea.blob'),
    disableExperimentalSEAWarning: true,
    useSnapshot: false,
    useCodeCache: false,
    assets,
  }, null, 2));

  // Generated by the Node version being embedded, not the one running this script.
  execFileSync(await hostNode(), ['--experimental-sea-config', configPath], { stdio: ['ignore', 'ignore', 'inherit'] });
  const blob = path.join(BUILD, 'sea.blob');
  console.log(`   ${(fs.statSync(blob).size / 1024 / 1024).toFixed(1)} MB`);
  return blob;
}

/**
 * Remove the Authenticode signature from a Windows binary.
 *
 * Injecting the SEA blob appends data after the signed region, which leaves the
 * signature pointing at the wrong bytes. Windows and antivirus treat a malformed
 * signature far worse than no signature at all - the file may refuse to launch.
 * Node's own SEA docs say to strip it first with `signtool remove /s`, which is
 * Windows-only, so we edit the PE header directly instead: clear the certificate
 * table entry and drop the certificate data off the end.
 */
function stripAuthenticode(file) {
  const buf = fs.readFileSync(file);
  const pe = buf.readUInt32LE(0x3c);
  if (buf.toString('ascii', pe, pe + 4) !== 'PE\0\0') throw new Error(`${file} is not a PE binary`);

  const isPE32Plus = buf.readUInt16LE(pe + 24) === 0x20b;
  const numDirs = buf.readUInt32LE(pe + 24 + (isPE32Plus ? 108 : 92));
  if (numDirs < 5) return { stripped: false, reason: 'no certificate directory' };

  const certEntry = pe + 24 + (isPE32Plus ? 112 : 96) + 4 * 8;
  const certOffset = buf.readUInt32LE(certEntry);
  const certSize = buf.readUInt32LE(certEntry + 4);
  if (!certOffset || !certSize) return { stripped: false, reason: 'already unsigned' };

  buf.writeUInt32LE(0, certEntry);
  buf.writeUInt32LE(0, certEntry + 4);
  // The checksum no longer matches. Windows only enforces it for drivers, and a
  // zero reads as "not computed" rather than as a wrong value.
  buf.writeUInt32LE(0, pe + 24 + 64);

  // The certificate blob sits at the end of a pristine binary; anything after it
  // would be appended data, which a freshly downloaded node.exe does not have.
  const end = certOffset + certSize === buf.length ? certOffset : buf.length;
  fs.writeFileSync(file, buf.subarray(0, end));
  return { stripped: true, bytes: buf.length - end };
}

/** Downloads via a temp file and renames on success, so an interrupted transfer is never cached as complete. */
function download(url, dest) {
  const tmp = `${dest}.partial`;
  return new Promise((resolve, reject) => {
    const request = (target, redirects = 0) => {
      https.get(target, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          if (redirects > 5) return reject(new Error('Too many redirects'));
          res.resume();
          return request(res.headers.location, redirects + 1);
        }
        if (res.statusCode !== 200) {
          res.resume();
          return reject(new Error(`${target} returned ${res.statusCode}`));
        }
        const file = fs.createWriteStream(tmp);
        res.pipe(file);
        file.on('finish', () => file.close(() => {
          fs.renameSync(tmp, dest);
          resolve(dest);
        }));
        file.on('error', (err) => {
          fs.rmSync(tmp, { force: true });
          reject(err);
        });
      }).on('error', (err) => {
        fs.rmSync(tmp, { force: true });
        reject(err);
      });
    };
    request(url);
  });
}

async function buildTarget(name, target, blob) {
  const output = path.join(DIST, target.file);
  fs.mkdirSync(DIST, { recursive: true });

  let base;
  if (target.tarball) {
    base = await hostNode();
  } else {
    // Version is part of the cache filename so changing NODE_VERSION downloads
    // the matching binary instead of reusing the previous one.
    base = path.join(BUILD, `node-${NODE_VERSION}-${name}`);
    if (!fs.existsSync(base)) {
      process.stdout.write(`   downloading node ${NODE_VERSION} for ${name}... `);
      await download(target.url, base);
      console.log(`${(fs.statSync(base).size / 1024 / 1024).toFixed(0)} MB`);
    }
  }

  fs.copyFileSync(base, output);
  fs.chmodSync(output, 0o755);

  if (name.startsWith('win')) {
    const result = stripAuthenticode(output);
    console.log(result.stripped
      ? `   stripped the Authenticode signature (${result.bytes} bytes) before injecting`
      : `   signature: ${result.reason}`);
  }

  execFileSync(path.join(ROOT, 'node_modules', '.bin', 'postject'), [
    output, 'NODE_SEA_BLOB', blob,
    '--sentinel-fuse', 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
  ], { stdio: ['ignore', 'ignore', 'inherit'] });

  console.log(`   ${target.file} - ${(fs.statSync(output).size / 1024 / 1024).toFixed(0)} MB`);

  if (target.smokeTest) smokeTest(output);
  return output;
}

/**
 * Run the freshly built binary in an empty directory and confirm it unpacks its
 * files and answers a command. Only possible for the target matching this
 * machine, but every target is built from the same blob, so a pass here means
 * the blob itself is sound.
 */
function smokeTest(binary) {
  const sandbox = fs.mkdtempSync(path.join(os.tmpdir(), 'sea-smoke-'));
  try {
    const copy = path.join(sandbox, path.basename(binary));
    fs.copyFileSync(binary, copy);
    fs.chmodSync(copy, 0o755);
    const out = execFileSync(copy, ['sessions'], { cwd: sandbox, encoding: 'utf8', timeout: 60000 });

    const unpacked = ASSETS.filter((rel) => fs.existsSync(path.join(sandbox, rel)));
    if (unpacked.length !== ASSETS.length) {
      throw new Error(`unpacked ${unpacked.length}/${ASSETS.length} assets`);
    }
    if (!/No sessions yet|[a-z]+-\d{8}/.test(out)) throw new Error(`unexpected output: ${out.slice(0, 120)}`);
    console.log(`   smoke test passed - unpacks ${ASSETS.length} files and runs`);
  } catch (err) {
    throw new Error(`smoke test FAILED for ${path.basename(binary)}: ${err.message}`);
  } finally {
    fs.rmSync(sandbox, { recursive: true, force: true });
  }
}

const only = process.argv[2];
const bundlePath = bundle();
const blob = await buildBlob(bundlePath);

console.log('3. Injecting into the Node binary for each platform...');
for (const [name, target] of Object.entries(TARGETS)) {
  if (only && only !== name) continue;
  try {
    await buildTarget(name, target, blob);
  } catch (err) {
    console.error(`   ${name} FAILED: ${err.message}`);
  }
}
console.log(`\nExecutables are in ${DIST}`);
